---
- name: Assert usage of systemd as an init system
  assert:
    that: ansible_service_mgr == 'systemd'
    msg: "This module only works with systemd"

- name: Get systemd version
  command: systemctl --version
  changed_when: false
  check_mode: false
  register: __systemd_version
  tags:
    - skip_ansible_lint

- name: Set systemd version fact
  set_fact:
    loki_systemd_version: "{{ __systemd_version.stdout_lines[0].split(' ')[-1] }}"

- block:
    - name: Get latest release
      uri:
        url: "https://api.github.com/repos/grafana/loki/releases/latest"
        method: GET
        return_content: true
        status_code: 200
        body_format: json
        validate_certs: false
        user: "{{ lookup('env', 'GH_USER') | default(omit) }}"
        password: "{{ lookup('env', 'GH_TOKEN') | default(omit) }}"
      no_log: "{{ not lookup('env', 'ANSIBLE_DEBUG') | bool }}"
      register: _latest_release
      until: _latest_release.status == 200
      retries: 5

    - name: "Set loki version to {{ _latest_release.json.tag_name[1:] }}"
      set_fact:
        loki_version: "{{ _latest_release.json.tag_name[1:] }}"
  when:
    - loki_version == "latest"
    - loki_binary_local_dir | length == 0
    - not loki_skip_install

- block:
    - name: "Get checksum list"
      set_fact:
        __loki_checksums: "{{ lookup('url', 'https://github.com/grafana/loki/releases/download/v' + loki_version + '/SHA256SUMS', wantlist=True) | list }}"
      run_once: true

    - name: "Get checksum for {{ go_arch }} architecture"
      set_fact:
        __loki_checksum: "{{ item.split(' ')[0] }}"
      with_items: "{{ __loki_checksums }}"
      when:
        - "('loki-linux-' + go_arch + '.zip') in item"
  delegate_to: localhost
  when:
    - loki_binary_local_dir | length == 0
    - not loki_skip_install
